### PR TITLE
Added ability to disable conversion warning

### PR DESCRIPTION
**Pull request by ryuoryuo**

### CODE REVIEW

**Comment by borislit** [comment]
@ryuoryuo looks good! Can you please add a test for that? Thanks

**Comment by ryuoryuo** [comment]
> @ryuoryuo looks good! Can you please add a test for that? Thanks

Done. Not sure if this is the correct way to update the config stub, but couldn't find a better way.

**Comment by borislit** [comment]
Thanks for the PR @ryuoryuo !

**Pull request merged**
