### PR TITLE
feat(isJSX): Add support for optional chainning

### LINKED ISSUE #120: Why can't I export this component?
Screenshot from 2020-09-26 12-59-00

For some weird reason the options to extract this component ↑ don't show up when I click the light bulb.
However, if I select this component ↓, then the option shows up, why is that?

Screenshot from 2020-09-26 13-02-10

### PR DESCRIPTION
**Pull request by eifr0980**
# Description 
Add support for optional chaining in JS\TS.
Closes #120 

> _NOTE:_ feature untested yet

### CODE REVIEW

**Comment by mattvague** [comment]
Would love to see this merged as it's quite often getting in the way of using glean in my react / typescript project. Anything I can do to help?

**Comment by borislit** [comment]
@mattvague check it out :)

**Comment by mattvague** [comment]
> @mattvague check it out :)

Amazing, thank you!

**Pull request merged**
